### PR TITLE
Fix latest data version

### LINKED ISSUE #215: Make sure latest data version is also available as specific data  / folder name

### PR DESCRIPTION
**Pull request by Aeilert**
Make sure latest data version is available as specific folder name.

Closes #215.

### CODE REVIEW

File: R/create_lkups.R [hunk 1]
```diff
@@ -10,14 +10,14 @@ create_versioned_lkups <- function(data_dir) {
...
+  # versions[1] <- "latest_release"
 
   versions_paths <- purrr::map(data_dirs, create_lkups, versions = versions)
-
   names(versions_paths) <- versions
 
   return(list(versions = versions,
-              versions_paths = versions_paths))
+              versions_paths = versions_paths,
+              latest_release = versions[1]))
```
Comment (tonyfujs) [inline R/create_lkups.R:20]: We'll just need to be careful here once we start adding version folders for PPPs and testing. Related to the email Andres sent.

**Review by tonyfujs — APPROVED** [review]
Thanks @Aeilert 
Looks good. I have a bunch of unit tests failing, but I think this is related to other PRs not being merged.

File: R/create_lkups.R (hunk 1 above)
Comment (Aeilert) [reply R/create_lkups.R:20]: Yep. Fully agree. We need to be very careful with the sorting and matching here. See also my commit here https://github.com/PIP-Technical-Team/pipapi/pull/219/commits/0f9192fa07f52bb2460d0670aa75fe2cb3a50d3d. We can modify this when we have agreed on the new folder structure.
